version: '3.1'
networks:
    app-tier:
        driver: bridge
services:
    app:
        networks:
            - app-tier
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        container_name: formify-backend
        links:
            - db
        depends_on:
            - db
        restart: always
        ports:
            - '4000:4000'
        expose:
            - '4000'

    nginx:
        networks:
            - app-tier
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        container_name: formify-frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
            - ../certbot/conf:/etc/letsencrypt
            - ../certbot/www:/var/www/certbot
        links:
            - app
        depends_on:
            - app
        restart: always
        ports:
            - '80:80'
            - '443:443'
        expose:
            - '80'
            - '443'
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    certbot:
        image: certbot/certbot
        container_name: certbot_service
        volumes:
            - ../certbot/conf:/etc/letsencrypt
            - ../certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    db:
        networks:
            - app-tier
        env_file: ./.env
        image: mysql:5.7
        volumes:
            - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
            - /home/ubuntu/db-formify:/var/lib/mysql
        container_name: formify-database
        environment:
            - MYSQL_DATABASE=${DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - TZ="Asia/Seoul"
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        restart: always
